name: unittest
on:
  push:
    branches:
      - "*"
      - "!develop"
      - "!master"
  pull_request:
    branches:
      - "*"
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install && npm install --only=dev
      - run: npm run test
